# Generated by Django 4.2.17 on 2025-04-12 00:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpandraharaha', '0054_mariazy_firenena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ded', models.CharField(max_length=3, verbose_name='DED')),
                ('daty_ded', models.DateField(default=datetime.datetime.now, verbose_name='Daty nanaovana DED')),
                ('fandaniana', models.IntegerField()),
                ('sata', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé')], default='en_cours', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Ded',
            },
        ),
        migrations.CreateModel(
            name='Rafitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe', models.CharField(choices=[('asa_fitoriana_filazantsara', 'Asa Fitoriana Filazantsara'), ('asa_fanabeazana', 'Asa Fanabeazana'), ('asa_sosialy', 'Asa Sosialy'), ('asa_iombonana', 'Asa Iombonana')], max_length=30)),
                ('fanamarihana', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rafitra',
            },
        ),
        migrations.CreateModel(
            name='Laminasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daty', models.DateField(default=datetime.datetime.now)),
                ('asa', models.CharField(blank=True, max_length=100, null=True)),
                ('toerana', models.CharField(blank=True, max_length=50, null=True)),
                ('fanamarihana', models.CharField(blank=True, max_length=200, null=True)),
                ('tossaafiko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laminasa_tossaafiko', to='mpandraharaha.tossaafiko')),
            ],
            options={
                'verbose_name_plural': 'Laminasa',
            },
        ),
        migrations.CreateModel(
            name='Kaonty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isa', models.IntegerField()),
                ('anarana', models.CharField(blank=True, max_length=50, null=True)),
                ('rafitra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaonty_rafitra', to='fitantanambola.rafitra')),
            ],
            options={
                'verbose_name_plural': 'Kaonty',
            },
        ),
        migrations.CreateModel(
            name='Fanamarinana_ded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ded', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitantanambola.ded')),
                ('mpanamarina_birao_ssa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpanamarina_toby_ssa', to=settings.AUTH_USER_MODEL)),
                ('mpanamarina_birao_tvf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpanamarina_birao_tvf', to=settings.AUTH_USER_MODEL)),
                ('mpanamarina_toby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpanamarina_toby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diarimbola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vola', models.IntegerField()),
                ('fanamarihana', models.CharField(blank=True, max_length=200, null=True)),
                ('kaonty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_kaonty', to='fitantanambola.kaonty')),
            ],
            options={
                'verbose_name_plural': 'Diarimbola',
            },
        ),
        migrations.AddField(
            model_name='ded',
            name='diarimbola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ded_diarimbola', to='fitantanambola.diarimbola'),
        ),
        migrations.AddField(
            model_name='ded',
            name='laminasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_laminasa', to='fitantanambola.laminasa'),
        ),
        migrations.AddField(
            model_name='ded',
            name='mpitantsorabola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpitantsorabola', to=settings.AUTH_USER_MODEL, verbose_name='Mpitantsoratry ny vola'),
        ),
        migrations.AddField(
            model_name='ded',
            name='tossaafiko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ded_tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
    ]
