# Generated by Django 4.2.17 on 2025-04-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0056_alter_mpikambana_taona'),
        ('fitantanambola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarimbola',
            name='tossaafiko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
    ]
