# Generated by Django 4.2.17 on 2025-04-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpandraharaha', '0056_alter_mpikambana_taona'),
        ('fitantanambola', '0002_diarimbola_tossaafiko'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaonty',
            name='tossaafiko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaonty_tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
        migrations.AlterField(
            model_name='fanamarinana_ded',
            name='mpanamarina_birao_ssa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpanamarina_toby_ssa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fanamarinana_ded',
            name='mpanamarina_birao_tvf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpanamarina_birao_tvf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fanamarinana_ded',
            name='mpanamarina_toby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpanamarina_toby', to=settings.AUTH_USER_MODEL),
        ),
    ]
