# Generated by Django 4.2.17 on 2025-04-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0003_kaonty_tossaafiko_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fanamarinana_ded',
        ),
    ]
