# Generated by Django 4.2.17 on 2025-04-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0004_delete_fanamarinana_ded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaonty',
            options={'verbose_name_plural': 'Kaontytvf'},
        ),
        migrations.RemoveField(
            model_name='diarimbola',
            name='kaonty',
        ),
        migrations.RemoveField(
            model_name='diarimbola',
            name='vola',
        ),
        migrations.RemoveField(
            model_name='kaonty',
            name='tossaafiko',
        ),
        migrations.AddField(
            model_name='diarimbola',
            name='ecart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diarimbola',
            name='taona',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='diarimbola',
            name='vola_ambiny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diarimbola',
            name='vola_holaniana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diarimbola',
            name='vola_lany',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laminasa',
            name='taona',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='laminasa',
            name='tombana',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ded',
        ),
    ]
