# Generated by Django 4.2.17 on 2025-04-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0005_alter_kaonty_options_remove_diarimbola_kaonty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarimbola',
            name='kaonty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_kaonty', to='fitantanambola.kaonty'),
        ),
    ]
