# Generated by Django 4.2.17 on 2025-04-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0056_alter_mpikambana_taona'),
        ('fitantanambola', '0006_diarimbola_kaonty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kaonty',
            new_name='KaontyTvf',
        ),
        migrations.CreateModel(
            name='KaontyTossaafiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isa', models.IntegerField()),
                ('anarana', models.CharField(blank=True, max_length=50, null=True)),
                ('kaontytvf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaontytvf', to='fitantanambola.kaontytvf')),
                ('tossaafiko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaonty_tossaafiko', to='mpandraharaha.tossaafiko')),
            ],
            options={
                'verbose_name_plural': 'KaontyTossaafiko',
            },
        ),
        migrations.AddField(
            model_name='laminasa',
            name='kaonty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laminasa_kaonty', to='fitantanambola.kaontytossaafiko'),
        ),
        migrations.AlterField(
            model_name='diarimbola',
            name='kaonty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_kaonty', to='fitantanambola.kaontytossaafiko'),
        ),
    ]
