# Generated by Django 4.2.17 on 2025-04-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0007_rename_kaonty_kaontytvf_kaontytossaafiko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminasa',
            name='diarimbola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laminasa_diarimbola', to='fitantanambola.diarimbola'),
        ),
    ]
