# Generated by Django 4.2.17 on 2025-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0008_laminasa_diarimbola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminasa',
            name='kaonty',
        ),
    ]
