# Generated by Django 4.2.17 on 2025-04-18 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0056_alter_mpikambana_taona'),
        ('fitantanambola', '0009_remove_laminasa_kaonty'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taona', models.CharField(blank=True, max_length=4, null=True)),
                ('daty', models.DateField(default=datetime.datetime.now)),
                ('miditra', models.IntegerField(default=0)),
                ('mivoaka', models.IntegerField(default=0)),
                ('ded', models.CharField(blank=True, max_length=4, null=True)),
                ('pj_ded', models.ImageField(blank=True, null=True, upload_to='pieces')),
                ('pj_edr', models.ImageField(blank=True, null=True, upload_to='pieces')),
                ('edr', models.CharField(blank=True, max_length=4, null=True)),
                ('fanamarihana', models.CharField(blank=True, max_length=200, null=True)),
                ('diarimbola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_diarimbola', to='fitantanambola.diarimbola')),
                ('tossaafiko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_tossaafiko', to='mpandraharaha.tossaafiko')),
            ],
            options={
                'verbose_name_plural': 'JournalCaisse',
            },
        ),
    ]
