# Generated by Django 4.2.17 on 2025-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0010_journalcaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcaisse',
            name='solde',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
