# Generated by Django 4.2.17 on 2025-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0011_journalcaisse_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcaisse',
            name='solde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
