# Generated by Django 4.2.17 on 2025-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0012_alter_journalcaisse_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarimbola',
            name='ecart',
            field=models.IntegerField(default=0, verbose_name=' % Fandaniana '),
        ),
    ]
