# Generated by Django 4.2.17 on 2025-05-03 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fitantanambola.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitantanambola', '0016_alter_diarimbola_user_alter_journalcaisse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarimbola',
            name='user',
            field=models.ForeignKey(blank=True, default=fitantanambola.models.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalcaisse',
            name='user',
            field=models.ForeignKey(blank=True, default=fitantanambola.models.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kaontytossaafiko',
            name='user',
            field=models.ForeignKey(blank=True, default=fitantanambola.models.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laminasa',
            name='user',
            field=models.ForeignKey(blank=True, default=fitantanambola.models.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
