# Generated by Django 4.2.17 on 2025-05-03 15:10

from django.db import migrations, models
import django.db.models.deletion
import fitantanambola.models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0057_alter_ankohonana_anarana'),
        ('fitantanambola', '0017_alter_diarimbola_user_alter_journalcaisse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarimbola',
            name='taona',
            field=models.CharField(blank=True, default=2025, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='diarimbola',
            name='tossaafiko',
            field=models.ForeignKey(default=fitantanambola.models.get_current_tossaafiko, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
        migrations.AlterField(
            model_name='journalcaisse',
            name='taona',
            field=models.CharField(blank=True, default=2025, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='journalcaisse',
            name='tossaafiko',
            field=models.ForeignKey(default=fitantanambola.models.get_current_tossaafiko, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
        migrations.AlterField(
            model_name='laminasa',
            name='taona',
            field=models.CharField(blank=True, default=2025, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='laminasa',
            name='tossaafiko',
            field=models.ForeignKey(default=fitantanambola.models.get_current_tossaafiko, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laminasa_tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
    ]
