# Generated by Django 4.2.17 on 2025-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0018_alter_diarimbola_taona_alter_diarimbola_tossaafiko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcaisse',
            name='fanamarihana_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fanamarihana'),
        ),
        migrations.AlterField(
            model_name='journalcaisse',
            name='fanamarihana',
            field=models.CharField(blank=True, choices=[('reliquat', 'Reliquat'), ('hafa', 'Hafa')], max_length=200, null=True, verbose_name='Sata'),
        ),
    ]
