# Generated by Django 4.2.17 on 2025-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0019_journalcaisse_fanamarihana_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcaisse',
            name='fanamarihana',
            field=models.CharField(blank=True, choices=[('reliquat', 'Reliquat'), ('hafa', 'Hafa')], default='Hafa', max_length=200, null=True, verbose_name='Sata'),
        ),
    ]
