# Generated by Django 4.2.17 on 2025-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitantanambola', '0020_alter_journalcaisse_fanamarihana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcaisse',
            name='fanamarihana',
            field=models.CharField(blank=True, choices=[('reliquat', 'reliquat'), ('annulation', 'annulation')], max_length=200, null=True, verbose_name='Sata'),
        ),
    ]
