# Generated by Django 4.2.17 on 2025-05-22 07:13

from django.db import migrations, models
import django.db.models.deletion
import fitantanambola.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mpandraharaha",
            "0060_alter_ankohonana_anarana_alter_mpiangona_anarana_and_more",
        ),
        ("fitantanambola", "0022_kaontytvf_faritra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kaontytossaafiko",
            name="anarana",
            field=models.CharField(
                blank=True, help_text="Libellée", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kaontytossaafiko",
            name="isa",
            field=models.IntegerField(help_text="Sous-Compte TOSSAAFIKO"),
        ),
        migrations.AlterField(
            model_name="kaontytossaafiko",
            name="tossaafiko",
            field=models.ForeignKey(
                default=fitantanambola.models.get_current_tossaafiko,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kaonty_tossaafiko",
                to="mpandraharaha.tossaafiko",
            ),
        ),
        migrations.AlterField(
            model_name="kaontytvf",
            name="anarana",
            field=models.CharField(
                blank=True,
                help_text="Famaritana ny Kaonty na Libellé",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kaontytvf",
            name="faritra",
            field=models.CharField(
                blank=True,
                choices=[("ivelany", "Ivelany"), ("anatiny", "Anatiny")],
                help_text="Asa ivelany na anatiny",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kaontytvf",
            name="isa",
            field=models.IntegerField(help_text="N° Kaonty"),
        ),
        migrations.AlterField(
            model_name="kaontytvf",
            name="rafitra",
            field=models.ForeignKey(
                help_text="AXE",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kaonty_rafitra",
                to="fitantanambola.rafitra",
            ),
        ),
    ]
