# Generated by Django 4.2.17 on 2025-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitantanambola", "0023_alter_kaontytossaafiko_anarana_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalcaisse",
            name="fanamarihana",
            field=models.CharField(
                blank=True,
                choices=[("reliquat", "reliquat"), ("annulation", "annulation")],
                max_length=300,
                null=True,
                verbose_name="Sata",
            ),
        ),
        migrations.AlterField(
            model_name="journalcaisse",
            name="fanamarihana_1",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Fanamarihana"
            ),
        ),
        migrations.AlterField(
            model_name="laminasa",
            name="asa",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="laminasa",
            name="fanamarihana",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="laminasa",
            name="toerana",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
