# Generated by Django 4.2.17 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetibola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarimbola',
            name='daty',
        ),
        migrations.AlterField(
            model_name='rafitra',
            name='axe',
            field=models.CharField(choices=[('asa_fitoriana_filazantsara', 'Asa Fitoriana Filazantsara'), ('asa_fanabeazana', 'Asa Fanabeazana'), ('asa_sosialy', 'Asa Sosialy'), ('asa_iombonana', 'Asa Iombonana')], max_length=30),
        ),
    ]
