# Generated by Django 4.2.17 on 2025-04-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tetibola', '0003_remove_diarimbola_laminasa_ded_laminasa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ded',
            options={'verbose_name_plural': 'Ded'},
        ),
        migrations.RemoveField(
            model_name='ded',
            name='fitambarany',
        ),
    ]
