# Generated by Django 4.2.17 on 2025-03-27 08:29

import ckeditor_uploader.fields
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpiangona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='pgn', unique=True)),
                ('name', models.CharField(default='vaovao', max_length=100)),
                ('surname', models.CharField(default='vaovao', max_length=100)),
                ('image', models.ImageField(default='i8.jpg', upload_to='mpiangona')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am an Amazing Vendor', null=True)),
                ('address', models.CharField(default='Antananarivo', max_length=100)),
                ('contact', models.CharField(default='+261 (34) 99 999 999', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mpiangonas',
            },
        ),
    ]
