# Generated by Django 4.2.17 on 2025-03-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpiangona',
            options={'verbose_name_plural': 'Mpiangona'},
        ),
    ]
