# Generated by Django 4.2.17 on 2025-03-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0002_alter_mpiangona_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='description',
            field=models.TextField(blank=True, default='I am an Amazing Vendor', null=True),
        ),
    ]
