# Generated by Django 4.2.17 on 2025-03-27 08:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0003_alter_mpiangona_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am an Amazing Vendor', null=True),
        ),
    ]
