# Generated by Django 4.2.17 on 2025-03-27 10:28

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0005_rename_vid_mpiangona_piid_mpandray'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ankohonana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='pad', unique=True)),
                ('faritra', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ankohonana',
            },
        ),
        migrations.RenameField(
            model_name='mpandray',
            old_name='Fiangonana',
            new_name='fiangonana',
        ),
        migrations.AlterField(
            model_name='mpandray',
            name='mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpandray', to='mpandraharaha.mpiangona'),
        ),
        migrations.AddField(
            model_name='mpiangona',
            name='ankohonana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ankohonana', to='mpandraharaha.ankohonana'),
        ),
    ]
