# Generated by Django 4.2.17 on 2025-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0006_ankohonana_rename_fiangonana_mpandray_fiangonana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankohonana',
            name='anarana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
