# Generated by Django 4.2.17 on 2025-04-03 07:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0007_ankohonana_anarana'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpiangona',
            name='toerana',
            field=models.CharField(default='Zanaka', help_text="Toerana misy azy eo anivon'ny ankohonana", max_length=100),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='address',
            field=models.CharField(default='Antananarivo', max_length=100, verbose_name='Adiresy'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='contact',
            field=models.CharField(default='+261 (34) 99 999 999', max_length=100, verbose_name='Finday'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Mpiangona ato FJKM Tranovato Faravohitra', null=True),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='image',
            field=models.ImageField(default='i8.jpg', upload_to='mpiangona', verbose_name='Sary'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='name',
            field=models.CharField(default='vaovao', max_length=100, verbose_name='Anarana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='surname',
            field=models.CharField(default='vaovao', max_length=100, verbose_name="Fanampin'anarana"),
        ),
    ]
