# Generated by Django 4.2.17 on 2025-04-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0008_mpiangona_toerana_alter_mpiangona_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpiangona',
            name='zanaka',
            field=models.IntegerField(default=0, help_text="Isan'ny zanaka", max_length=2, verbose_name='Zanaka'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='ankohonana',
            field=models.ForeignKey(help_text="Mitondra ny anaran'ny Ray lohan'ny fianakaviana", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ankohonana', to='mpandraharaha.ankohonana'),
        ),
    ]
