# Generated by Django 4.2.17 on 2025-04-03 08:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0009_mpiangona_zanaka_alter_mpiangona_ankohonana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Mpiangona ato FJKM Tranovato Faravohitra', null=True, verbose_name='Mombamomba'),
        ),
    ]
