# Generated by Django 4.2.17 on 2025-04-03 13:26

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0010_alter_mpiangona_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpandray',
            name='karatra',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[V|L]-\\d\\d\\d\\d')]),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='contact',
            field=models.CharField(help_text='034 10 466 70', max_length=100, validators=[django.core.validators.RegexValidator('^\\d\\d\\d \\d\\d \\d\\d\\d \\d\\d', message='Tsy atao abd fa tarehimarika ary asiana elanelany')], verbose_name='Finday'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Mpiangona ato FJKM Tranovato Faravohitra', help_text='Filazana ny mombamomba ny mpiangona', null=True, verbose_name='Fanamarihana'),
        ),
    ]
