# Generated by Django 4.2.17 on 2025-04-03 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0012_alter_mpandray_karatra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpandray',
            name='karatra',
            field=models.CharField(blank=True, help_text='V-0000 na L-0000', max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[V|L]-\\d\\d\\d\\d', message="Atao mitovy amin'ny ohatra io ambany io azafady")]),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='contact',
            field=models.CharField(help_text='034 10 466 70', max_length=13, validators=[django.core.validators.RegexValidator('^\\d\\d\\d \\d\\d \\d\\d\\d \\d\\d', message='Tsy atao abd fa tarehimarika ary asiana elanelany')], verbose_name='Finday'),
        ),
    ]
