# Generated by Django 4.2.17 on 2025-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0013_alter_mpandray_karatra_alter_mpiangona_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='description',
            field=models.CharField(blank=True, default='Mpiangona ato FJKM Tranovato Faravohitra', help_text='Filazana ny mombamomba ny mpiangona', max_length=500, null=True, verbose_name='Fanamarihana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Anarana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='surname',
            field=models.CharField(max_length=100, verbose_name="Fanampin'anarana"),
        ),
    ]
