# Generated by Django 4.2.17 on 2025-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0014_alter_mpiangona_description_alter_mpiangona_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='zanaka',
            field=models.IntegerField(default=0, help_text="Isan'ny zanaka", verbose_name='Zanaka'),
        ),
    ]
