# Generated by Django 4.2.17 on 2025-04-06 19:22

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0015_alter_mpiangona_zanaka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpandray',
            name='mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpandray_mpiangona', to='mpandraharaha.mpiangona'),
        ),
        migrations.CreateModel(
            name='Sampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='said', unique=True)),
                ('anarana', models.CharField(choices=[('stk', 'STK'), ('ssa', 'SSA')], default='ssa', max_length=10)),
                ('andraikitra', models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina')], default='filoha', max_length=15)),
                ('fanamarihana', models.TextField()),
                ('mpiangona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampana_mpiangona', to='mpandraharaha.mpiangona')),
            ],
        ),
    ]
