# Generated by Django 4.2.17 on 2025-04-06 19:41

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0016_alter_mpandray_mpiangona_sampana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tossaafiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='said', unique=True)),
                ('anarana', models.CharField(choices=[('stk', 'STK'), ('ssa', 'SSA'), ('ssa', 'FDL'), ('ssa', 'SSA')], default='ssa', max_length=10, verbose_name='tossaafiko')),
                ('andraikitra', models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina')], default='filoha', max_length=15)),
                ('fanamarihana', models.TextField(blank=True, null=True)),
                ('mpiangona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tossaafiko_mpiangona', to='mpandraharaha.mpiangona')),
            ],
            options={
                'verbose_name_plural': 'Tossaafiko',
            },
        ),
        migrations.DeleteModel(
            name='Sampana',
        ),
    ]
