# Generated by Django 4.2.17 on 2025-04-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0018_alter_tossaafiko_anarana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpandray',
            name='mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpiangona', to='mpandraharaha.mpiangona'),
        ),
        migrations.AlterField(
            model_name='tossaafiko',
            name='mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpandraharaha.mpiangona'),
        ),
    ]
