# Generated by Django 4.2.17 on 2025-04-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0019_alter_mpandray_mpiangona_alter_tossaafiko_mpiangona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpandray',
            name='mpiangona',
        ),
        migrations.RemoveField(
            model_name='tossaafiko',
            name='mpiangona',
        ),
        migrations.AddField(
            model_name='mpandray',
            name='mpandray_mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpandray_mpiangona', to='mpandraharaha.mpiangona'),
        ),
        migrations.AddField(
            model_name='tossaafiko',
            name='tossaafiko_mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tossaafiko_mpiangona', to='mpandraharaha.mpiangona'),
        ),
    ]
