# Generated by Django 4.2.17 on 2025-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0020_remove_mpandray_mpiangona_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tossaafiko',
        ),
    ]
