# Generated by Django 4.2.17 on 2025-04-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0022_tossaafiko'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tossaafiko',
        ),
    ]
