# Generated by Django 4.2.17 on 2025-04-07 07:27

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0023_delete_tossaafiko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tossaafiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='said', unique=True)),
                ('anarana', models.CharField(choices=[('stk', 'STK'), ('ssa', 'SSA'), ('fdl', 'FDL'), ('toby_fifaliana', 'Toby Fifaliana'), ('toby_fitiavana', 'Toby Fitiavana'), ('toby_fahamarinana', 'Toby Fahamarinana'), ('toby_fiadanana', 'Toby Fiadanana')], default='ssa', max_length=17, verbose_name='tossaafiko')),
                ('andraikitra', models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina'), ('mpiakambana', 'Mpikambana')], default='filoha', max_length=15)),
                ('fanamarihana', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tossaafiko',
            },
        ),
        migrations.AddField(
            model_name='mpiangona',
            name='tossaafiko',
            field=models.ManyToManyField(blank=True, null=True, related_name='tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
    ]
