# Generated by Django 4.2.17 on 2025-04-07 07:45

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0024_tossaafiko_mpiangona_tossaafiko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpiangona',
            name='tossaafiko',
        ),
        migrations.RemoveField(
            model_name='tossaafiko',
            name='andraikitra',
        ),
        migrations.CreateModel(
            name='Mpikambana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pikid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='pikid', unique=True)),
                ('andraikitra', models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina'), ('mpiakambana', 'Mpikambana')], max_length=15)),
                ('mpiangona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpandraharaha.mpiangona')),
                ('tossaafiko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpandraharaha.tossaafiko')),
            ],
            options={
                'verbose_name_plural': 'Mpikambana',
            },
        ),
    ]
