# Generated by Django 4.2.17 on 2025-04-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0025_remove_mpiangona_tossaafiko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpikambana',
            name='tossaafiko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tossaafiko', to='mpandraharaha.tossaafiko'),
        ),
    ]
