# Generated by Django 4.2.17 on 2025-04-07 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0026_alter_mpikambana_tossaafiko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpandray',
            name='mpandray_mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpandray_mpiangona', to='mpandraharaha.mpiangona', verbose_name='Mpiangona'),
        ),
        migrations.AlterField(
            model_name='mpikambana',
            name='andraikitra',
            field=models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina'), ('mpiakambana', 'Mpikambana'), ('mpitarika_rantsana', 'Mpitarika Rantsana'), ('mpianatra_ssa', 'Mpianatra SSA'), ('mpampianatra_ssa', 'Mpampianatra SSA')], max_length=18),
        ),
    ]
