# Generated by Django 4.2.17 on 2025-04-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0027_alter_mpandray_mpandray_mpiangona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpiangona',
            old_name='address',
            new_name='adiresy',
        ),
        migrations.RenameField(
            model_name='mpiangona',
            old_name='name',
            new_name='anarana',
        ),
        migrations.RenameField(
            model_name='mpiangona',
            old_name='description',
            new_name='fanamarihana',
        ),
        migrations.RenameField(
            model_name='mpiangona',
            old_name='surname',
            new_name='fanampiny',
        ),
        migrations.RenameField(
            model_name='mpiangona',
            old_name='contact',
            new_name='finday',
        ),
        migrations.RenameField(
            model_name='mpiangona',
            old_name='image',
            new_name='sary',
        ),
    ]
