# Generated by Django 4.2.17 on 2025-04-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0028_rename_address_mpiangona_adiresy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpandray',
            old_name='mpandray_mpiangona',
            new_name='mpiangona',
        ),
        migrations.AlterField(
            model_name='mpikambana',
            name='mpiangona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpikambana_mpiangona', to='mpandraharaha.mpiangona'),
        ),
        migrations.AlterField(
            model_name='tossaafiko',
            name='anarana',
            field=models.CharField(choices=[('stk', 'STK'), ('ssa', 'SSA'), ('fdl', 'FDL'), ('aam', 'AAM'), ('safi', 'SAFI'), ('toby_fifaliana', 'Toby Fifaliana'), ('toby_fitiavana', 'Toby Fitiavana'), ('toby_fahamarinana', 'Toby Fahamarinana'), ('toby_fiadanana', 'Toby Fiadanana')], default='ssa', max_length=17, verbose_name='tossaafiko'),
        ),
    ]
