# Generated by Django 4.2.17 on 2025-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0029_rename_mpandray_mpiangona_mpandray_mpiangona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpiangona',
            name='anarana_zatovo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anarana zatovo'),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='anarana',
            field=models.CharField(blank=True, help_text="Anaran'ny raim-pianakaviana", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='faritra',
            field=models.CharField(blank=True, help_text="faritra misy ny toerana hipetrahan'ny ankohonana", max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='mpandray',
            name='fiangonana',
            field=models.CharField(help_text='Fiangonana nanamasinana ho mpandray', max_length=50),
        ),
        migrations.AlterField(
            model_name='mpandray',
            name='taona',
            field=models.DateField(help_text='Taona naha mpandray'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='anarana',
            field=models.CharField(max_length=30, verbose_name='Anarana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='fanampiny',
            field=models.CharField(max_length=25, verbose_name="Fanampin'anarana"),
        ),
        migrations.AlterField(
            model_name='mpikambana',
            name='andraikitra',
            field=models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina'), ('mpiakambana', 'Mpikambana'), ('mpitarika_rantsana', 'Mpitarika Rantsana'), ('mpianatra_ssa', 'Mpianatra SSA'), ('mpampianatra_ssa', 'Mpampianatra SSA')], help_text="Andraikitra ao amin'ny Tossaafiko", max_length=18),
        ),
        migrations.AlterField(
            model_name='tossaafiko',
            name='anarana',
            field=models.CharField(choices=[('stk', 'STK'), ('ssa', 'SSA'), ('fdl', 'FDL'), ('aam', 'AAM'), ('safi', 'SAFI'), ('toby_fifaliana', 'Toby Fifaliana'), ('toby_fitiavana', 'Toby Fitiavana'), ('toby_fahamarinana', 'Toby Fahamarinana'), ('toby_fiadanana', 'Toby Fiadanana')], default='ssa', help_text="Anarana oentin'ny Tossaafiko", max_length=17, verbose_name='tossaafiko'),
        ),
        migrations.AlterField(
            model_name='tossaafiko',
            name='fanamarihana',
            field=models.TextField(blank=True, help_text='Ny mombamomba ny Tossaafiko', null=True),
        ),
    ]
