# Generated by Django 4.2.17 on 2025-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0030_mpiangona_anarana_zatovo_alter_ankohonana_anarana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpikambana',
            name='andraikitra',
            field=models.CharField(choices=[('filoha', 'Filoha'), ('filoha_mpanampy', 'Filoha Mpanampy'), ('tonia', 'Mpitan-tsoratry ny fivoriana'), ('tonia_vola', 'Mpitan-tsoratry ny vola'), ('mpitahiry_vola', 'Mpitahiry Vola'), ('mpanolo_tsaina', 'Mpanolo-tsaina'), ('mpikambana', 'Mpikambana'), ('mpitarika_rantsana', 'Mpitarika Rantsana'), ('mpianatra_ssa', 'Mpianatra SSA'), ('mpampianatra_ssa', 'Mpampianatra SSA'), ('coach_rantsana', 'Coaach Rantsana'), ('mpitarika_sampati', 'Mpitarika Sampati')], help_text="Andraikitra ao amin'ny Tossaafiko", max_length=18),
        ),
        migrations.AlterField(
            model_name='tossaafiko',
            name='anarana',
            field=models.CharField(choices=[('stk', 'STK'), ('ssa', 'SSA'), ('fdl', 'FDL'), ('aam', 'AAM'), ('safif', 'SAFIF'), ('fafi', 'FAFI'), ('fmo', 'FMO'), ('svm', 'SVM'), ('dorkasy', 'DORKASY'), ('vfl', 'VFL'), ('zr', 'ZR'), ('sampati', 'SAMPATI'), ('amboarampeo', 'AMBOARAMPEO'), ('aff', 'AFF'), ('kpsv', 'KPSV'), ('kga', 'KGA'), ('kff', 'KFF'), ('kvo', 'KVO'), ('kftl', 'KFTL'), ('kmb', 'KMB'), ('tpram', 'TPRAM'), ('toby_fifaliana', 'TOBY FIFALIANA'), ('toby_fitiavana', 'TOBY FITIAVANA'), ('toby_fahamarinana', 'TOBY FAHAMARINANA'), ('toby_fiadanana', 'TOBY FIADANANA')], default='ssa', help_text="Anarana oentin'ny Tossaafiko", max_length=17, unique=True, verbose_name='tossaafiko'),
        ),
    ]
