# Generated by Django 4.2.17 on 2025-04-08 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0032_alter_tossaafiko_anarana'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpiangona',
            name='daty_nahaterahana',
            field=models.DateField(auto_now=True, verbose_name='Daty nahaterahana'),
        ),
        migrations.AddField(
            model_name='mpiangona',
            name='finday_2',
            field=models.CharField(blank=True, help_text='034 10 466 70', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d \\d\\d \\d\\d\\d \\d\\d', message='Tsy atao abd fa tarehimarika ary asiana elanelany')], verbose_name='Finday hafa'),
        ),
        migrations.AddField(
            model_name='mpiangona',
            name='mailaka',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Mailaka'),
        ),
        migrations.AlterField(
            model_name='tossaafiko',
            name='anarana',
            field=models.CharField(choices=[('stk', 'STK'), ('ktt', 'KTT'), ('ssa', 'SSA'), ('fdl', 'FDL'), ('aam', 'AAM'), ('safif', 'SAFIF'), ('fafi', 'FAFI'), ('fmo', 'FMO'), ('svm', 'SVM'), ('dorkasy', 'DORKASY'), ('vfl', 'VFL'), ('zr', 'ZR'), ('sampati', 'SAMPATI'), ('amboarampeo', 'AMBOARAMPEO'), ('aff', 'AFF'), ('kpsv', 'KPSV'), ('kga', 'KGA'), ('kff', 'KFF'), ('kvo', 'KVO'), ('kftl', 'KFTL'), ('kmb', 'KMB'), ('tpram', 'TPRAM'), ('toby_fifaliana', 'TOBY FIFALIANA'), ('toby_fitiavana', 'TOBY FITIAVANA'), ('toby_fahamarinana', 'TOBY FAHAMARINANA'), ('toby_fiadanana', 'TOBY FIADANANA')], default='ssa', error_messages={'required': 'Efa misy io anarana io'}, help_text="Anarana oentin'ny Tossaafiko", max_length=17, unique=True, verbose_name='tossaafiko'),
        ),
    ]
