# Generated by Django 4.2.17 on 2025-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0033_mpiangona_daty_nahaterahana_mpiangona_finday_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='daty_nahaterahana',
            field=models.DateField(blank=True, verbose_name='Daty nahaterahana'),
        ),
    ]
