# Generated by Django 4.2.17 on 2025-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0034_alter_mpiangona_daty_nahaterahana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='daty_nahaterahana',
            field=models.DateField(auto_now=True, verbose_name='Daty nahaterahana'),
        ),
    ]
