# Generated by Django 4.2.17 on 2025-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0036_remove_ankohonana_ankid_remove_mpandray_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='daty_nahaterahana',
            field=models.DateField(blank=True, null=True, verbose_name='Daty nahaterahana'),
        ),
    ]
