# Generated by Django 4.2.17 on 2025-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0037_alter_mpiangona_daty_nahaterahana'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankohonana',
            name='faritra_tvf',
            field=models.CharField(blank=True, help_text="faritra misy ny toerana hipetrahan'ny ankohonana nofaritan'ny TVF", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ankohonana',
            name='firenena',
            field=models.CharField(blank=True, help_text='Firenena misy azy ankehitriny', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ankohonana',
            name='fokotany',
            field=models.CharField(blank=True, help_text="Anaran'ny raim-pianakaviana", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mpiangona',
            name='asa',
            field=models.CharField(max_length=50, null=True, verbose_name='Asa'),
        ),
        migrations.AddField(
            model_name='mpiangona',
            name='fanomezana',
            field=models.CharField(max_length=50, null=True, verbose_name='Fanomezam-pahasoavana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='mailaka',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mailaka'),
        ),
    ]
