# Generated by Django 4.2.17 on 2025-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0038_ankohonana_faritra_tvf_ankohonana_firenena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='asa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Asa'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='fanomezana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fanomezam-pahasoavana'),
        ),
    ]
