# Generated by Django 4.2.17 on 2025-04-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0039_alter_mpiangona_asa_alter_mpiangona_fanomezana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpandray',
            name='mpiangona',
        ),
        migrations.RemoveField(
            model_name='mpikambana',
            name='mpiangona',
        ),
        migrations.AddField(
            model_name='mpandray',
            name='mpandray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpandray_mpiangona', to='mpandraharaha.mpiangona', verbose_name='Mpandray'),
        ),
        migrations.AddField(
            model_name='mpikambana',
            name='mpikambana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpikambana', to='mpandraharaha.mpiangona'),
        ),
        migrations.CreateModel(
            name='Atolotra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atolotra_mpiangona', to='mpandraharaha.mpiangona', verbose_name='Zaza natolotra')),
            ],
            options={
                'verbose_name_plural': 'Atolotra',
            },
        ),
    ]
