# Generated by Django 4.2.17 on 2025-04-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0041_rename_zaza_atolotra_atolotra_atolotra_daty_batisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batisa',
            old_name='batisa',
            new_name='zaza',
        ),
        migrations.RemoveField(
            model_name='batisa',
            name='daty',
        ),
        migrations.AddField(
            model_name='batisa',
            name='daty_batisa',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty batisa'),
        ),
        migrations.AddField(
            model_name='batisa',
            name='daty_nanolorana',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty nanolorana'),
        ),
        migrations.AlterField(
            model_name='batisa',
            name='rad',
            field=models.ManyToManyField(blank=True, null=True, to='mpandraharaha.mpiangona', verbose_name='Ray aman-dReny'),
        ),
        migrations.DeleteModel(
            name='Atolotra',
        ),
    ]
