# Generated by Django 4.2.17 on 2025-04-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0042_rename_batisa_batisa_zaza_remove_batisa_daty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batisa',
            name='rad',
        ),
    ]
