# Generated by Django 4.2.17 on 2025-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0043_remove_batisa_rad'),
    ]

    operations = [
        migrations.AddField(
            model_name='batisa',
            name='rad',
            field=models.ManyToManyField(blank=True, null=True, to='mpandraharaha.mpiangona', verbose_name='Ray aman-dReny'),
        ),
    ]
