# Generated by Django 4.2.17 on 2025-04-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0044_batisa_rad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batisa',
            name='zaza',
        ),
        migrations.AddField(
            model_name='batisa',
            name='anarana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batisa_mpiangona', to='mpandraharaha.mpiangona', verbose_name='Anarana'),
        ),
    ]
