# Generated by Django 4.2.17 on 2025-04-09 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0045_remove_batisa_zaza_batisa_anarana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katekomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andiany', models.CharField(blank=True, help_text="Anarana oentin'ny andian'ny katekomena", max_length=20, null=True)),
                ('daty', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty batisa')),
                ('fiangonana', models.CharField(blank=True, help_text='Fiangonana namoahana azy', max_length=50, null=True)),
                ('firenena', models.CharField(blank=True, help_text='Firenena namoahana azy', max_length=25, null=True)),
                ('anarana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='katekomena_mpiangona', to='mpandraharaha.mpiangona', verbose_name='Anarana')),
            ],
            options={
                'verbose_name_plural': 'Batisa',
            },
        ),
    ]
