# Generated by Django 4.2.17 on 2025-04-09 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0046_katekomena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katekomena',
            name='daty',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty'),
        ),
    ]
