# Generated by Django 4.2.17 on 2025-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0047_alter_katekomena_daty'),
    ]

    operations = [
        migrations.AddField(
            model_name='batisa',
            name='fiangonana',
            field=models.CharField(blank=True, help_text='Fiangonana nanaovana batisa', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batisa',
            name='firenena',
            field=models.CharField(blank=True, help_text='Firenena nanaovana batisa', max_length=25, null=True),
        ),
    ]
