# Generated by Django 4.2.17 on 2025-04-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0048_batisa_fiangonana_batisa_firenena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katekomena',
            options={'verbose_name_plural': 'Katekomena'},
        ),
    ]
