# Generated by Django 4.2.17 on 2025-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0049_alter_katekomena_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='katekomena',
            name='sata',
            field=models.CharField(choices=[('mianatra', 'Mianatra'), ('mpandray', 'Mpandray')], default='mianatra', max_length=15),
        ),
    ]
