# Generated by Django 4.2.17 on 2025-04-09 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0050_katekomena_sata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katekomena',
            name='daty',
        ),
        migrations.AddField(
            model_name='katekomena',
            name='daty_nidirana',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty nidirana nianatra'),
        ),
        migrations.AddField(
            model_name='katekomena',
            name='daty_nivoahana',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty nivoahana katekomena'),
        ),
    ]
