# Generated by Django 4.2.17 on 2025-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0051_remove_katekomena_daty_katekomena_daty_nidirana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankohonana',
            name='faritra',
            field=models.CharField(blank=True, help_text="faritra misy ny toerana hipetrahan'ny ankohonana", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='faritra_tvf',
            field=models.CharField(blank=True, help_text="faritra misy ny toerana hipetrahan'ny ankohonana nofaritan'ny TVF", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='firenena',
            field=models.CharField(blank=True, help_text='Firenena misy azy ankehitriny', max_length=25, null=True),
        ),
    ]
