# Generated by Django 4.2.17 on 2025-04-09 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0052_alter_ankohonana_faritra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mariazy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daty_sivily', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty sivily')),
                ('kaominina', models.CharField(blank=True, help_text='Kaominina', max_length=50, null=True)),
                ('daty_fiangonana', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Daty Fiangonana')),
                ('fiangonana', models.CharField(blank=True, help_text='Fiangonana', max_length=25, null=True)),
                ('lahy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpiangona_lahy', to='mpandraharaha.mpiangona', verbose_name="Anaran'ny lahy")),
                ('vavy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpiangona_vavy', to='mpandraharaha.mpiangona', verbose_name="Anaran'ny vavy")),
            ],
            options={
                'verbose_name_plural': 'Mariazy',
            },
        ),
    ]
