# Generated by Django 4.2.17 on 2025-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0053_mariazy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariazy',
            name='firenena',
            field=models.CharField(blank=True, help_text='Firenena namoahana azy', max_length=25, null=True),
        ),
    ]
