# Generated by Django 4.2.17 on 2025-04-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0054_mariazy_firenena'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpikambana',
            name='taona',
            field=models.CharField(blank=True, help_text='Mandat', max_length=15, verbose_name='Taom-piasana'),
        ),
    ]
