# Generated by Django 4.2.17 on 2025-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0055_mpikambana_taona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpikambana',
            name='taona',
            field=models.CharField(blank=True, choices=[('2020-2024', '2020-2024'), ('2025-2028', '2025-2028')], help_text='Mandat', max_length=15, verbose_name='Taom-piasana'),
        ),
    ]
