# Generated by Django 4.2.17 on 2025-04-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0056_alter_mpikambana_taona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankohonana',
            name='anarana',
            field=models.CharField(blank=True, help_text="Anaran'ny raim-pianakaviana", max_length=50, null=True, unique=True),
        ),
    ]
