# Generated by Django 4.2.17 on 2025-05-05 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0057_alter_ankohonana_anarana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpiangona',
            name='ankohonana',
            field=models.ForeignKey(blank=True, help_text="Mitondra ny anaran'ny Ray lohan'ny fianakaviana", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ankohonana', to='mpandraharaha.ankohonana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='finday',
            field=models.CharField(blank=True, help_text='034 10 466 70', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d \\d\\d \\d\\d\\d \\d\\d', message='Tsy atao abd fa tarehimarika ary asiana elanelany')], verbose_name='Finday'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='sary',
            field=models.ImageField(blank=True, default='i8.jpg', null=True, upload_to='mpiangona', verbose_name='Sary'),
        ),
    ]
