# Generated by Django 4.2.17 on 2025-05-07 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpandraharaha', '0058_alter_mpiangona_ankohonana_alter_mpiangona_finday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankohonana',
            name='anarana',
            field=models.CharField(blank=True, help_text="Anaran'ny raim-pianakaviana", max_length=50, null=True, unique=True, verbose_name='Anarana feno'),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='faritra',
            field=models.CharField(blank=True, help_text="Faritra misy ny toerana hipetrahan'ny ankohonana", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='faritra_tvf',
            field=models.CharField(blank=True, help_text="Faritra misy ny toerana hipetrahan'ny ankohonana nofaritan'ny TVF", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='firenena',
            field=models.CharField(blank=True, default='Madagasikara', help_text='Firenena misy azy ankehitriny', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ankohonana',
            name='fokotany',
            field=models.CharField(blank=True, help_text="Fokotany misy ny toerana hipetrahan'ny ankohonana", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batisa',
            name='daty_batisa',
            field=models.DateField(blank=True, null=True, verbose_name='Daty batisa'),
        ),
        migrations.AlterField(
            model_name='batisa',
            name='daty_nanolorana',
            field=models.DateField(blank=True, null=True, verbose_name='Daty nanolorana'),
        ),
        migrations.AlterField(
            model_name='batisa',
            name='firenena',
            field=models.CharField(blank=True, default='Madagasikara', help_text='Firenena nanaovana batisa', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='katekomena',
            name='daty_nivoahana',
            field=models.DateField(blank=True, null=True, verbose_name='Daty nivoahana katekomena'),
        ),
        migrations.AlterField(
            model_name='katekomena',
            name='fiangonana',
            field=models.CharField(blank=True, default='FJKM Tranovato Faravohitra', help_text='Fiangonana namoahana azy', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='katekomena',
            name='firenena',
            field=models.CharField(blank=True, default='Madagasikara', help_text='Firenena namoahana azy', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mariazy',
            name='daty_sivily',
            field=models.DateField(blank=True, null=True, verbose_name='Daty sivily'),
        ),
        migrations.AlterField(
            model_name='mariazy',
            name='fiangonana',
            field=models.CharField(blank=True, default='FJKM Tranovato Faravohitra', help_text='Fiangonana', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mariazy',
            name='firenena',
            field=models.CharField(blank=True, default='Madagasikara', help_text='Firenena namoahana azy', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mariazy',
            name='kaominina',
            field=models.CharField(blank=True, help_text='Kaominina nanaovana ny mariazy sivily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='adiresy',
            field=models.CharField(default='Lot: ', max_length=100, verbose_name='Adiresy'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='anarana',
            field=models.CharField(max_length=50, verbose_name='Anarana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='fanamarihana',
            field=models.CharField(blank=True, default=' ', help_text='Filazana ny mombamomba ny mpiangona', max_length=500, null=True, verbose_name='Fanamarihana'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='finday',
            field=models.CharField(blank=True, default='034 ', help_text='034 10 466 70', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d \\d\\d \\d\\d\\d \\d\\d', message='Tsy atao abd fa tarehimarika ary asiana elanelany')], verbose_name='Finday'),
        ),
        migrations.AlterField(
            model_name='mpiangona',
            name='toerana',
            field=models.CharField(default='Zanaka', help_text="Toerana misy azy eo anivon'ny ankohonana", max_length=100, verbose_name='Toerana'),
        ),
    ]
