# Generated by Django 4.2.17 on 2025-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mpandraharaha",
            "0059_alter_ankohonana_anarana_alter_ankohonana_faritra_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ankohonana",
            name="anarana",
            field=models.CharField(
                blank=True,
                help_text="Anaran'ny raim-pianakaviana",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Anarana feno",
            ),
        ),
        migrations.AlterField(
            model_name="mpiangona",
            name="anarana",
            field=models.CharField(max_length=100, verbose_name="Anarana"),
        ),
        migrations.AlterField(
            model_name="mpiangona",
            name="anarana_zatovo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Anarana zatovo"
            ),
        ),
        migrations.AlterField(
            model_name="mpiangona",
            name="fanampiny",
            field=models.CharField(max_length=100, verbose_name="Fanampin'anarana"),
        ),
    ]
