# Generated by Django 4.2.17 on 2025-04-11 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpandraharaha', '0054_mariazy_firenena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rafitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe', models.CharField(choices=[('asa_fitoriana_filazantsara', 'Asa Fitoriana Filazantsara'), ('asa_fanabeazana', 'Asa Fanabeazana'), ('asa_sosialy', 'Asa Fanabeazana'), ('asa_iombonana', 'Asa Iombonana')], max_length=30)),
                ('fanamarihana', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rafitra',
            },
        ),
        migrations.CreateModel(
            name='Laminasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daty', models.DateField(default=datetime.datetime.now)),
                ('asa', models.CharField(blank=True, max_length=100, null=True)),
                ('toerana', models.CharField(blank=True, max_length=50, null=True)),
                ('fanamarihana', models.CharField(blank=True, max_length=200, null=True)),
                ('tossaafiko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laminasa_tossaafiko', to='mpandraharaha.tossaafiko')),
            ],
            options={
                'verbose_name_plural': 'Laminasa',
            },
        ),
        migrations.CreateModel(
            name='Kaonty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isa', models.IntegerField()),
                ('anarana', models.CharField(blank=True, max_length=50, null=True)),
                ('rafitra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaonty_rafitra', to='tetibola.rafitra')),
            ],
            options={
                'verbose_name_plural': 'Kaonty',
            },
        ),
        migrations.CreateModel(
            name='Diarimbola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daty', models.DateField(default=datetime.datetime.now)),
                ('fanamarihana', models.CharField(blank=True, max_length=200, null=True)),
                ('vola', models.IntegerField()),
                ('kaonty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_kaonty', to='tetibola.kaonty')),
                ('laminasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarimbola_laminasa', to='tetibola.laminasa')),
            ],
            options={
                'verbose_name_plural': 'Diarimbola',
            },
        ),
        migrations.CreateModel(
            name='Ded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ded', models.CharField(max_length=3)),
                ('daty_ded', models.DateField(default=datetime.datetime.now)),
                ('fandaniana', models.IntegerField()),
                ('fitambarany', models.IntegerField()),
                ('diarimbola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ded_diarimbola', to='tetibola.diarimbola')),
                ('tossaafiko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ded_tossaafiko', to='mpandraharaha.tossaafiko')),
            ],
            options={
                'verbose_name_plural': 'Diarimbola',
            },
        ),
    ]
