# Generated by Django 4.2.17 on 2025-04-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tetibola', '0004_alter_ded_options_remove_ded_fitambarany'),
    ]

    operations = [
        migrations.AddField(
            model_name='ded',
            name='mpitantsorabola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpitantsorabola', to=settings.AUTH_USER_MODEL),
        ),
    ]
