# Generated by Django 4.2.17 on 2025-04-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tetibola', '0005_ded_mpitantsorabola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ded',
            name='mpitantsorabola',
        ),
    ]
