"""
Django settings for fjkmtvf project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

#Library for universal local language i8n
from django.conf.global_settings import LANGUAGES as DJANGO_LANGUAGES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#Conf using local language
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+11d=r0j4(d-s+)5i8*ftxeo582(inidl!ppy1xcervu@ip-qz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SITE_ID = 1

ALLOWED_HOSTS = ['fjkmtvf.pythonanywhere.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin', # 16/01/25
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    

    # Third Party
    # 'taggit',
    'ckeditor',
    'import_export',
    'guardian',
    'rangefilter',
    
        #app 
    'mpandraharaha',
    'fitantanambola',
    'maridrefy',
    'userauths',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #Local Conf Language Middleware
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fjkmtvf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Templates Conf-1 14/01/25
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fjkmtvf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'fjkmtvf$default',
#         'USER': 'fjkmtvf',
#         'PASSWORD': 'Problem_digital2025',
#         'HOST': 'fjkmtvf.mysql.pythonanywhere-services.com', 
#         'PORT': '3306',
#         'OPTIONS': {
# 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
# }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Nairobi/Kenya"

TIME_ZONE = 'UTC'

#Local Conf For Universal Language
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

USE_I18N = True

USE_TZ = True

# Library Configurating Universal Language
LANGUAGES = DJANGO_LANGUAGES


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

""" Statics & Media Configuration
    14/01/25
"""

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "welcome_sign": "Ataovy ho mpianatro ny firenena rehetra",
     "user_avatar": "avatar",
    'site_title' : "FJKM Tranovato Faravohitra",
    'site_header' : "FJKM TVF",
    'site_brand' : "FJKM TVF",
    'site_logo' : "assets/img/mpiangona/tvf.png",
    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",
    "copyright": "H&L.Co",
    # "search_model": ["userauths.User", "auth.Group"],
    
       # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        # {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Facebook", "url": "https://web.facebook.com/groups/36639447687/", "new_window": True},

        # model admin to link to (Permissions checked against model)
        # {"model": "mpandraharaha.Mpandray"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "mpandraharaha"},
        {"name": "Fitantanambola", "app":"fitantanambola"},
        
        
    ],

     "usermenu_links": [
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"name": "Ekipa KPSV", "model": "userauths.user"},
        {"name": "Permission", "model": "auth.group"}
    ],
     
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["userauths", "auth"],
    "show_ui_builder": True,
     
   "icons": {
        "mpandraharaha.Mpandray": "fas fa-users-cog",
        "mpandraharaha.Ankohonana": "fas fa-user",
        "mpandraharaha.Mpiangona": "fas fa-pray",
        "mpandraharaha.Mpikambana": "fas fa-user-friends",
        "mpandraharaha.Tossaafiko": "fas fa-users",
        "mpandraharaha.Batisa": "fas fa-graduation-cap",
        "mpandraharaha.Katekomena": "fas fa-user-graduate",
        "mpandraharaha.Mariazy": "fas fa-venus-mars",
        
        "fitantanambola.Diarimbola":"far fa-address-book",
        "fitantanambola.JournalCaisse":"fas fa-balance-scale",
        "fitantanambola.KaontyTvf":"fas fa-chart-pie",
        "fitantanambola.KaontyTossaafiko":"fas fa-piggy-bank",
        "fitantanambola.Laminasa":"fas fa-hand-holding-usd",
        "fitantanambola.Rafitra":"fas fa-landmark",
        
   },
   
    "related_modal_active": True,
    #Inlines Tab form
    "changeform_format": "horizontal_tab",
    #Activate Langage Choice. Need Config Setting i8N Before 
    "language_chooser": True,
     "use_google_fonts_cdn": True,
    
    # "changeform_format_overrides": {"auth.Groups": "vertical_tabs"},

}

#Theme Choice
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    # "dark_mode_theme": "flatly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}

#Activate Modal Source
X_FRAME_OPTIONS = 'SAMEORIGIN'

AUTH_USER_MODEL = 'userauths.User'

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    "default": {
         'skin': 'moono',
         'codesnIppet_theme': 'monokai',
         'toolbar': 'all',
         'extraPlugins': ','.join([
            'codesnippet',
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
        ]),
    }
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)