# Generated by Django 4.2.17 on 2025-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sondage',
            options={'verbose_name_plural': 'Sondage'},
        ),
        migrations.AlterField(
            model_name='sondage',
            name='anonymous',
            field=models.IntegerField(unique=True),
        ),
    ]
