# Generated by Django 4.2.17 on 2025-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0002_alter_sondage_options_alter_sondage_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='sigara',
            field=models.BooleanField(choices=[('1', 'ENY'), ('2', 'TSIA')], default=True),
        ),
    ]
