# Generated by Django 4.2.17 on 2025-04-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0003_sondage_sigara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='sigara',
        ),
    ]
