# Generated by Django 4.2.17 on 2025-04-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0004_remove_sondage_sigara'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='sigara',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='anonymous',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
