# Generated by Django 4.2.17 on 2025-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0005_sondage_sigara_alter_sondage_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='anonymous',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='sondage',
            constraint=models.UniqueConstraint(fields=('anonymous',), name='anonymous_unique_constrain', violation_error_message='Book with this name already exists.'),
        ),
    ]
