# Generated by Django 4.2.17 on 2025-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0006_alter_sondage_anonymous_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sondage',
            name='anonymous_unique_constrain',
        ),
        migrations.AlterField(
            model_name='sondage',
            name='anonymous',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
