# Generated by Django 4.2.17 on 2025-04-30 14:08

from django.db import migrations, models
import maridrefy.models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0007_remove_sondage_anonymous_unique_constrain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='anonymous',
            field=models.IntegerField(default=maridrefy.models.get_current_user, unique=True),
        ),
    ]
