# Generated by Django 4.2.17 on 2025-04-30 14:32

from django.db import migrations, models
import maridrefy.models


class Migration(migrations.Migration):

    dependencies = [
        ('maridrefy', '0008_alter_sondage_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='anonymous',
            field=models.IntegerField(default=maridrefy.models.get_current_user),
        ),
    ]
